### ISSUE TITLE
Another issue with Java Part of the https://codelabs.solace.dev/codelabs/design-document-discover-develop-event-driven-apis

### ISSUE THREAD

**Issue by soutchilin** [SolaceDev/solace-dev-codelabs#169]
Hi,

Sorry for remark, but it is pretty frustrating to have a step-by-step lab that doesn't work. I've made a Solace course where, if I recall it right, the lab was mentioned there. 

Anyway, the exported AsyncAPI file and description for code generation doesn't work at all. TL;TW - just try to get the Java code compiled by following the description and you'll meet all the issues.

**Comment by Mrc0113** [comment]
I'm going to add onto this. We need to review the entire codelab. 

Another issue was found with the help of @soutchilin. In section 11 It looks like we are adding the `x-scs-destination` to the `subscribe` operation instead of the `publish` operation. This issue was likely introduce when the Event Portal switched from exporting the `x-view: provider` to the default `x-view: client`.

**Comment by Mrc0113** [comment]
Closed by #188
