### ISSUE TITLE
The link checker doesn't seem to catch the broken Boomi documentation link

### ISSUE THREAD

**Issue by bjb-solace** [SolaceDev/solace-dev-codelabs#194]
It's hard to read the link checker output but I didn't see the broken link reported here:  https://github.com/SolaceDev/solace-dev-codelabs/issues/193 in the link checker output.

**Comment by TamimiGitHub** [comment]
Hey - reason why the link checker did not catch it is because the link is not "actually" broken. Meaning that it doesnt return a 404 since Boomi help docs catch the broken link and return a valid page like below
<img width="1785" alt="Screen Shot 2022-04-06 at 4 42 25 PM" src="https://user-images.githubusercontent.com/6826053/162091901-9c104b6a-4f57-42ed-b3ba-ab5e90e44dd7.png">
 I have update the link in the codelab
